### PR TITLE
Change samples to be built as windowed application.

### PR DESCRIPTION
**Pull request by fungos**
Got your changes and fixed windows compilation.
Also merged again with latest working bgfx. :)

### CODE REVIEW

**Comment by floooh** [comment]
Heh, good timing, I just tried compiling with my own changes on Windows and saw the linker errors ;)

**Comment by floooh** [comment]
Tested on Windows(7) and OSX and all working fine. Thanks!

**Comment by bkaradzic** [comment]
Those fips configs seem too laborious. in GENie examples are done this way (just giving you idea to make it more concise):

Function:
https://github.com/bkaradzic/bgfx/blob/master/scripts/genie.lua#L111

And then:
https://github.com/bkaradzic/bgfx/blob/master/scripts/genie.lua#L385

**Comment by floooh** [comment]
True, we could wrap this also into a cmake function, wouldn't look as nice as Lua of course ;)

We would need to glob the requires files per sample with file(GLOB ...). I'm also wondering whether it makes sense to allow file patterns inside fips_files() (or may be add a new fips_glob_files() function). The downside is that cmake wouldn't automatically re-run when adding new files to the CMakeLists.txt files (right now this happens automatically during the build when CMakeLists.txt files are modified).

**Comment by fungos** [comment]
Yes, true. But that is because I haven't made it the right way(tm) yet.
I've something in the works to improve most of this in a simple and generic way. 
But, then there are things like this entry point situation. I do not know exactly how to make it transparent as in practice subsystem:windows expects WinMain. How does GENie works with mainCRTStartup? I couldn't find it anywhere, is it magical? :)

Anyway, @floooh, I'm doing some tests with a version of fips_files (no good name yet) that accepts  path(s) and|or regular expression(s) for globing files. It should be able to do the combo fips_dir + fips_files recursively and applying a regex filter on each entry for example.

This with a new function bgfx_app() will be as simple as doing:

```
bgfx_app(00-helloworld)
...
bgfx_app(27-terrain)
```

And projects that import fips-bgfx will also be able to simple use something like: `bgfx_app(my_super_game PATH src/)`.

**Comment by floooh** [comment]
sounds good :)

**Pull request merged**
